### ISSUE TITLE
xcode13 compile error

### ISSUE THREAD

**Issue by xintenggiegie** [NordicSemiconductor/IOS-DFU-Library#456]
CBService 's property is changed to optional
`weak open var peripheral: CBPeripheral? { get }`

**Comment by emoonadev** [comment]
Same problem in Xcode 13

**Comment by emoonadev** [comment]
Merged fix to develop for the [issue](https://github.com/NordicSemiconductor/IOS-DFU-Library/issues/454#issuecomment-922871516)

**Comment by philips77** [comment]
Are you developing for iOS or Mac?

**Comment by philips77** [comment]
This change has been addressed in 4.10.4, as far as i remember. But seems like Apple made it more interesting and now the API diverged between iOS and Mac. We #455 tries to address that issue no matter the target.

**Comment by xintenggiegie** [comment]
Sorry, I'm using an older version。😂 @philips77

**Comment by rodmaz** [comment]
We are using version 4.11.0 (Swift Package) and still getting these issues when the app is compiled in release mode/archive.

**Comment by philips77** [comment]
Fix released in 4.11.1.
